/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package crudapps.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import crudapps.model.CrudApps;
import crudapps.model.CrudAppsModel;
import crudapps.model.CrudAppsSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CrudApps service. Represents a row in the &quot;CrudApps_CrudApps&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CrudAppsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CrudAppsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CrudAppsImpl
 * @generated
 */
@JSON(strict = true)
public class CrudAppsModelImpl
	extends BaseModelImpl<CrudApps> implements CrudAppsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a crud apps model instance should use the <code>CrudApps</code> interface instead.
	 */
	public static final String TABLE_NAME = "CrudApps_CrudApps";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"appId", Types.BIGINT},
		{"title", Types.VARCHAR}, {"description", Types.VARCHAR},
		{"url", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("appId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("url", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CrudApps_CrudApps (uuid_ VARCHAR(75) null,appId LONG not null primary key,title VARCHAR(75) null,description VARCHAR(75) null,url VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table CrudApps_CrudApps";

	public static final String ORDER_BY_JPQL = " ORDER BY crudApps.appId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CrudApps_CrudApps.appId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long UUID_COLUMN_BITMASK = 1L;

	public static final long APPID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CrudApps toModel(CrudAppsSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CrudApps model = new CrudAppsImpl();

		model.setUuid(soapModel.getUuid());
		model.setAppId(soapModel.getAppId());
		model.setTitle(soapModel.getTitle());
		model.setDescription(soapModel.getDescription());
		model.setUrl(soapModel.getUrl());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CrudApps> toModels(CrudAppsSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CrudApps> models = new ArrayList<CrudApps>(soapModels.length);

		for (CrudAppsSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public CrudAppsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _appId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAppId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _appId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CrudApps.class;
	}

	@Override
	public String getModelClassName() {
		return CrudApps.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CrudApps, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CrudApps, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CrudApps, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((CrudApps)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CrudApps, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CrudApps, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CrudApps)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CrudApps, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CrudApps, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CrudApps>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CrudApps.class.getClassLoader(), CrudApps.class,
			ModelWrapper.class);

		try {
			Constructor<CrudApps> constructor =
				(Constructor<CrudApps>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<CrudApps, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CrudApps, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CrudApps, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<CrudApps, Object>>();
		Map<String, BiConsumer<CrudApps, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<CrudApps, ?>>();

		attributeGetterFunctions.put("uuid", CrudApps::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<CrudApps, String>)CrudApps::setUuid);
		attributeGetterFunctions.put("appId", CrudApps::getAppId);
		attributeSetterBiConsumers.put(
			"appId", (BiConsumer<CrudApps, Long>)CrudApps::setAppId);
		attributeGetterFunctions.put("title", CrudApps::getTitle);
		attributeSetterBiConsumers.put(
			"title", (BiConsumer<CrudApps, String>)CrudApps::setTitle);
		attributeGetterFunctions.put("description", CrudApps::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<CrudApps, String>)CrudApps::setDescription);
		attributeGetterFunctions.put("url", CrudApps::getUrl);
		attributeSetterBiConsumers.put(
			"url", (BiConsumer<CrudApps, String>)CrudApps::setUrl);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getAppId() {
		return _appId;
	}

	@Override
	public void setAppId(long appId) {
		_appId = appId;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public String getUrl() {
		if (_url == null) {
			return "";
		}
		else {
			return _url;
		}
	}

	@Override
	public void setUrl(String url) {
		_url = url;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, CrudApps.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CrudApps toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CrudApps>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CrudAppsImpl crudAppsImpl = new CrudAppsImpl();

		crudAppsImpl.setUuid(getUuid());
		crudAppsImpl.setAppId(getAppId());
		crudAppsImpl.setTitle(getTitle());
		crudAppsImpl.setDescription(getDescription());
		crudAppsImpl.setUrl(getUrl());

		crudAppsImpl.resetOriginalValues();

		return crudAppsImpl;
	}

	@Override
	public int compareTo(CrudApps crudApps) {
		long primaryKey = crudApps.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CrudApps)) {
			return false;
		}

		CrudApps crudApps = (CrudApps)object;

		long primaryKey = crudApps.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CrudApps> toCacheModel() {
		CrudAppsCacheModel crudAppsCacheModel = new CrudAppsCacheModel();

		crudAppsCacheModel.uuid = getUuid();

		String uuid = crudAppsCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			crudAppsCacheModel.uuid = null;
		}

		crudAppsCacheModel.appId = getAppId();

		crudAppsCacheModel.title = getTitle();

		String title = crudAppsCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			crudAppsCacheModel.title = null;
		}

		crudAppsCacheModel.description = getDescription();

		String description = crudAppsCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			crudAppsCacheModel.description = null;
		}

		crudAppsCacheModel.url = getUrl();

		String url = crudAppsCacheModel.url;

		if ((url != null) && (url.length() == 0)) {
			crudAppsCacheModel.url = null;
		}

		return crudAppsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CrudApps, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CrudApps, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CrudApps, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((CrudApps)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CrudApps, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CrudApps, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CrudApps, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CrudApps)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CrudApps>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _appId;
	private String _title;
	private String _description;
	private String _url;
	private long _columnBitmask;
	private CrudApps _escapedModel;

}