/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package crudapps.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CrudApps service. Represents a row in the &quot;CrudApps_CrudApps&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>crudapps.model.impl.CrudAppsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>crudapps.model.impl.CrudAppsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CrudApps
 * @generated
 */
@ProviderType
public interface CrudAppsModel extends BaseModel<CrudApps> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a crud apps model instance should use the {@link CrudApps} interface instead.
	 */

	/**
	 * Returns the primary key of this crud apps.
	 *
	 * @return the primary key of this crud apps
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this crud apps.
	 *
	 * @param primaryKey the primary key of this crud apps
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this crud apps.
	 *
	 * @return the uuid of this crud apps
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this crud apps.
	 *
	 * @param uuid the uuid of this crud apps
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the app ID of this crud apps.
	 *
	 * @return the app ID of this crud apps
	 */
	public long getAppId();

	/**
	 * Sets the app ID of this crud apps.
	 *
	 * @param appId the app ID of this crud apps
	 */
	public void setAppId(long appId);

	/**
	 * Returns the title of this crud apps.
	 *
	 * @return the title of this crud apps
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this crud apps.
	 *
	 * @param title the title of this crud apps
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this crud apps.
	 *
	 * @return the description of this crud apps
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this crud apps.
	 *
	 * @param description the description of this crud apps
	 */
	public void setDescription(String description);

	/**
	 * Returns the url of this crud apps.
	 *
	 * @return the url of this crud apps
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this crud apps.
	 *
	 * @param url the url of this crud apps
	 */
	public void setUrl(String url);

}